const questions = [
    // === DIS DONC! 5 (Зелёная тема) ===
    // Unit 1
    { de: "das Buch", fr: "le livre", book: 5, unit: 1 },
    { de: "das Lineal", fr: "la règle", book: 5, unit: 1 },
    { de: "der Ordner", fr: "le classeur", book: 5, unit: 1 },
    { de: "das Heft", fr: "le cahier", book: 5, unit: 1 },
    { de: "der Bleistift", fr: "le crayon", book: 5, unit: 1 },
    { de: "der Kugelschreiber", fr: "le stylo", book: 5, unit: 1 },
    { de: "der Gummi", fr: "la gomme", book: 5, unit: 1 },
    { de: "die Wandtafel", fr: "le tableau noir", book: 5, unit: 1 },
    { de: "das Etui", fr: "la trousse", book: 5, unit: 1 },
    { de: "der Tisch", fr: "la table", book: 5, unit: 1 },
    { de: "der Stuhl", fr: "la chaise", book: 5, unit: 1 },
    { de: "das Schulfach", fr: "la matière scolaire", book: 5, unit: 1 },
    { de: "Deutsch", fr: "l'allemand", book: 5, unit: 1 },
    { de: "Französisch", fr: "le français", book: 5, unit: 1 },
    { de: "Englisch", fr: "l'anglais", book: 5, unit: 1 },
    { de: "Mathematik", fr: "les mathématiques", book: 5, unit: 1 },
    { de: "die Wochentage", fr: "les jours de la semaine", book: 5, unit: 1 },
    { de: "Montag", fr: "lundi", book: 5, unit: 1 },
    { de: "Dienstag", fr: "mardi", book: 5, unit: 1 },
    { de: "Mittwoch", fr: "mercredi", book: 5, unit: 1 },
    { de: "Donnerstag", fr: "jeudi", book: 5, unit: 1 },
    { de: "Freitag", fr: "vendredi", book: 5, unit: 1 },
    { de: "Samstag", fr: "samedi", book: 5, unit: 1 },
    { de: "Sonntag", fr: "dimanche", book: 5, unit: 1 },
    { de: "eine Schule", fr: "une école", book: 5, unit: 1 },
    { de: "rechnen", fr: "calculer", book: 5, unit: 1 },
    { de: "zeichnen", fr: "dessiner", book: 5, unit: 1 },
    { de: "singen", fr: "chanter", book: 5, unit: 1 },
    { de: "experimentieren", fr: "expérimenter", book: 5, unit: 1 },
    { de: "Französisch sprechen", fr: "parler français", book: 5, unit: 1 },
    
    // Unit 2
    { de: "die Familie", fr: "la famille", book: 5, unit: 2 },
    { de: "ein Kind", fr: "un/une enfant", book: 5, unit: 2 },
    { de: "die Mutter", fr: "la mère, la maman", book: 5, unit: 2 },
    { de: "der Vater", fr: "le père, le papa", book: 5, unit: 2 },
    { de: "die Eltern", fr: "les parents", book: 5, unit: 2 },
    { de: "die Schwester", fr: "la sœur", book: 5, unit: 2 },
    { de: "der Bruder", fr: "le frère", book: 5, unit: 2 },
    { de: "die Grossmutter", fr: "la grand-mère", book: 5, unit: 2 },
    { de: "der Grossvater", fr: "le grand-père", book: 5, unit: 2 },
    { de: "die Grosseltern", fr: "les grands-parents", book: 5, unit: 2 },
    { de: "die Tante", fr: "la tante", book: 5, unit: 2 },
    { de: "ein Onkel", fr: "un oncle", book: 5, unit: 2 },
    { de: "die Cousine", fr: "la cousine", book: 5, unit: 2 },
    { de: "der Cousin", fr: "le cousin", book: 5, unit: 2 },
    { de: "das Baby, das Kleinkind", fr: "le bébé", book: 5, unit: 2 },
    { de: "die Tochter, das Mädchen", fr: "la fille", book: 5, unit: 2 },
    { de: "der Sohn", fr: "le fils", book: 5, unit: 2 },
    { de: "hier ist, da ist", fr: "voici, voilà", book: 5, unit: 2 },
    { de: "er ist, sie ist", fr: "il est, elle est", book: 5, unit: 2 },
    { de: "Lionel ist der Bruder von Nathalie.", fr: "Lionel est le frère de Nathalie.", book: 5, unit: 2 },
    { de: "sie sind", fr: "ils sont, elles sont", book: 5, unit: 2 },
    { de: "das ist", fr: "c'est", book: 5, unit: 2 },
    { de: "Das ist meine Familie.", fr: "C'est ma famille.", book: 5, unit: 2 },
    { de: "das sind", fr: "ce sont", book: 5, unit: 2 },
    { de: "Das sind meine Grosseltern.", fr: "Ce sont mes grands-parents.", book: 5, unit: 2 },
    { de: "wer?", fr: "qui?", book: 5, unit: 2 },
    { de: "er heisst, sie heisst", fr: "il s'appelle, elle s'appelle", book: 5, unit: 2 },
    { de: "sie heissen", fr: "ils s'appellent, elles s'appellent", book: 5, unit: 2 },
    { de: "der Steckbrief", fr: "la fiche personnelle", book: 5, unit: 2 },
    { de: "der Name", fr: "le nom", book: 5, unit: 2 },
    { de: "der Vorname", fr: "le prénom", book: 5, unit: 2 },
    { de: "die Sprache", fr: "la langue", book: 5, unit: 2 },
    { de: "Ich spreche Deutsch, Französisch und Englisch.", fr: "Je parle allemand, français et anglais.", book: 5, unit: 2 },

    // Unit 3
    { de: "die Freizeitbeschäftigung", fr: "le loisir", book: 5, unit: 3 },
    { de: "ein Computer", fr: "un ordinateur", book: 5, unit: 3 },
    { de: "der Fernseher", fr: "la télé", book: 5, unit: 3 },
    { de: "die Spielkonsole", fr: "la console", book: 5, unit: 3 },
    { de: "lesen", fr: "lire", book: 5, unit: 3 },
    { de: "Fussball (Spiel), Fussball spielen", fr: "le foot, faire du foot", book: 5, unit: 3 },
    { de: "das Velo, das Fahrrad", fr: "le vélo", book: 5, unit: 3 },
    { de: "der Ski", fr: "le ski", book: 5, unit: 3 },
    { de: "das Unihockey, Unihockey spielen", fr: "l'unihockey (m), faire de l'unihockey", book: 5, unit: 3 },
    { de: "tanzen", fr: "danser", book: 5, unit: 3 },
    { de: "schwimmen", fr: "nager", book: 5, unit: 3 },
    { de: "die Gitarre, Gitarre spielen", fr: "la guitare, jouer de la guitare", book: 5, unit: 3 },
    { de: "die Flöte", fr: "la flûte", book: 5, unit: 3 },
    { de: "das Klavier, Klavier spielen", fr: "le piano, jouer du piano", book: 5, unit: 3 },
    { de: "draussen spielen", fr: "jouer dehors", book: 5, unit: 3 },
    { de: "ein Tier, die Tiere", fr: "un animal, les animaux (m pl)", book: 5, unit: 3 },
    { de: "das Basteln", fr: "le bricolage", book: 5, unit: 3 },
    { de: "Musik hören", fr: "écouter de la musique", book: 5, unit: 3 },
    { de: "kochen", fr: "faire la cuisine", book: 5, unit: 3 },
    { de: "shoppen", fr: "faire du shopping", book: 5, unit: 3 },
    { de: "Freunde/Freundinnen treffen", fr: "rencontrer des amis/amies", book: 5, unit: 3 },
    { de: "lieben, ich liebe", fr: "aimer, j'aime", book: 5, unit: 3 },
    { de: "sehr gerne haben, ich habe sehr gerne", fr: "adorer, j'adore", book: 5, unit: 3 },
    { de: "meine Leidenschaft ist ...", fr: "ma passion, c'est...", book: 5, unit: 3 },
    { de: "mein Hobby ist ...", fr: "mon hobby, c'est...", book: 5, unit: 3 },
    { de: "ich bin Fan von ...", fr: "je suis fan de...", book: 5, unit: 3 },
    { de: "die Zahl", fr: "le nombre", book: 5, unit: 3 },
    { de: "ein Schüler, eine Schülerin", fr: "un/une élève", book: 5, unit: 3 },
    { de: "der Knabe", fr: "le garçon", book: 5, unit: 3 },
    { de: "das Mädchen, die Tochter", fr: "la fille", book: 5, unit: 3 },

    // Unit 4
    { de: "eine Zutat", fr: "un ingrédient", book: 5, unit: 4 },
    { de: "eine Ananas", fr: "un ananas", book: 5, unit: 4 },
    { de: "die grüne/blaue Traube", fr: "le raisin vert/bleu", book: 5, unit: 4 },
    { de: "die Erdbeere", fr: "la fraise", book: 5, unit: 4 },
    { de: "der weisse Champignon", fr: "le champignon blanc", book: 5, unit: 4 },
    { de: "die Gurkenscheibe", fr: "la rondelle de concombre", book: 5, unit: 4 },
    { de: "die Karotte", fr: "la carotte", book: 5, unit: 4 },
    { de: "die Birne", fr: "la poire", book: 5, unit: 4 },
    { de: "das Ananasblatt", fr: "la feuille d'ananas", book: 5, unit: 4 },
    { de: "die (Kirsch-)Tomate", fr: "la tomate (cerise)", book: 5, unit: 4 },
    { de: "ein wenig Petersilie", fr: "un peu de persil", book: 5, unit: 4 },
    { de: "das Gesicht", fr: "le visage", book: 5, unit: 4 },
    { de: "ein Ohr", fr: "une oreille", book: 5, unit: 4 },
    { de: "die Augen, ein Auge", fr: "les yeux (m pl), un œil", book: 5, unit: 4 },
    { de: "die Haare", fr: "les cheveux (m pl)", book: 5, unit: 4 },
    { de: "der Kopf", fr: "la tête", book: 5, unit: 4 },
    { de: "die Nase", fr: "le nez", book: 5, unit: 4 },
    { de: "der Mund", fr: "la bouche", book: 5, unit: 4 },
    { de: "die Zitronenscheibe", fr: "la rondelle de citron", book: 5, unit: 4 },
    { de: "Für die Nase nehme ich eine Karotte.", fr: "Pour le nez, je prends une carotte.", book: 5, unit: 4 },
    { de: "Was ist das?", fr: "C'est quoi?", book: 5, unit: 4 },
    { de: "die Banane", fr: "la banane", book: 5, unit: 4 },
    { de: "die Nudeln", fr: "les nouilles (f pl)", book: 5, unit: 4 },
    { de: "Spiesse eine Traube auf.", fr: "Pique un raisin.", book: 5, unit: 4 },
    { de: "Befestige die Traube an der Birne.", fr: "Fixe le raisin sur la poire.", book: 5, unit: 4 },
    { de: "Schneide (halbiere) die Ananas.", fr: "Coupe l'ananas (en deux).", book: 5, unit: 4 },
    { de: "Stelle/Lege die Erdbeere auf den Teller.", fr: "Pose la fraise sur l'assiette.", book: 5, unit: 4 },
    { de: "Nimm eine Birne für den Körper.", fr: "Prends une poire pour le corps.", book: 5, unit: 4 },
    { de: "Du schneidest. Schneide!", fr: "Tu coupes. Coupe.", book: 5, unit: 4 },
    { de: "Ihr schneidet. Schneidet!", fr: "Vous coupez. Coupez.", book: 5, unit: 4 },
    { de: "ein Alphabet", fr: "un alphabet", book: 5, unit: 4 },
    { de: "die Suppe", fr: "la soupe", book: 5, unit: 4 },
    { de: "der Buchstabe", fr: "la lettre", book: 5, unit: 4 },

    // Unit 5
    { de: "der Wolf", fr: "le loup", book: 5, unit: 5 },
    { de: "der Igel", fr: "le hérisson", book: 5, unit: 5 },
    { de: "das Murmeltier", fr: "la marmotte", book: 5, unit: 5 },
    { de: "eine Biene", fr: "une abeille", book: 5, unit: 5 },
    { de: "ein Wohnort", fr: "une adresse", book: 5, unit: 5 },
    { de: "die Grösse", fr: "la taille", book: 5, unit: 5 },
    { de: "das Gewicht", fr: "le poids", book: 5, unit: 5 },
    { de: "die Nahrung", fr: "la nourriture", book: 5, unit: 5 },
    { de: "hundert", fr: "cent", book: 5, unit: 5 },
    { de: "tausend", fr: "mille", book: 5, unit: 5 },
    { de: "die Katze", fr: "le chat", book: 5, unit: 5 },
    { de: "das Pferd", fr: "le cheval", book: 5, unit: 5 },
    { de: "das Schwein", fr: "le cochon", book: 5, unit: 5 },
    { de: "eine Schnecke", fr: "un escargot", book: 5, unit: 5 },
    { de: "das Kaninchen", fr: "le lapin", book: 5, unit: 5 },
    { de: "der Papagei", fr: "le perroquet", book: 5, unit: 5 },
    { de: "der Fisch", fr: "le poisson", book: 5, unit: 5 },
    { de: "die Kuh", fr: "la vache", book: 5, unit: 5 },
    { de: "die Farbe", fr: "la couleur", book: 5, unit: 5 },
    { de: "weiss", fr: "blanc/blanche", book: 5, unit: 5 },
    { de: "grau", fr: "gris/grise", book: 5, unit: 5 },
    { de: "schwarz", fr: "noir/noire", book: 5, unit: 5 },
    { de: "braun", fr: "brun/brune, marron", book: 5, unit: 5 },
    { de: "blau", fr: "bleu/bleue", book: 5, unit: 5 },
    { de: "grün", fr: "vert/verte", book: 5, unit: 5 },
    { de: "rot", fr: "rouge", book: 5, unit: 5 },
    { de: "gelb", fr: "jaune", book: 5, unit: 5 },
    { de: "rosa", fr: "rose", book: 5, unit: 5 },
    { de: "violett", fr: "violet/violette", book: 5, unit: 5 },
    { de: "orange", fr: "orange", book: 5, unit: 5 },
    { de: "Er/Sie lebt in den Bergen Europas.", fr: "Il/Elle vit dans les montagnes en Europe.", book: 5, unit: 5 },
    { de: "Er/Sie frisst (isst) Früchte.", fr: "Il/Elle mange des fruits.", book: 5, unit: 5 },
    { de: "Er/Sie misst 45 bis 60 Zentimeter.", fr: "Il/Elle mesure de 45 à 60 centimètres.", book: 5, unit: 5 },
    { de: "Er/Sie wiegt zwischen 5 und 10 Kilogramm.", fr: "Il/Elle pèse entre 5 et 10 kilos.", book: 5, unit: 5 },
    { de: "Er/Sie hat einen Schnabel.", fr: "Il/Elle a un bec.", book: 5, unit: 5 },
    { de: "Er/Sie ist grau und braun.", fr: "Il/Elle est gris/e et brun/e.", book: 5, unit: 5 },
    { de: "Welche Farbe hat das Schwein?", fr: "De quelle couleur est le cochon?", book: 5, unit: 5 },
    
    // Unit 6
    { de: "die Stadt", fr: "la ville", book: 5, unit: 6 },
    { de: "das Land", fr: "le pays", book: 5, unit: 6 },
    { de: "das Bauwerk", fr: "le monument", book: 5, unit: 6 },
    { de: "der Turm", fr: "la tour", book: 5, unit: 6 },
    { de: "gross", fr: "grand/grande", book: 5, unit: 6 },
    { de: "klein", fr: "petit/petite", book: 5, unit: 6 },
    { de: "rund", fr: "rond/ronde", book: 5, unit: 6 },
    { de: "rechteckig", fr: "rectangulaire", book: 5, unit: 6 },
    { de: "kurz", fr: "court/courte", book: 5, unit: 6 },
    { de: "lang", fr: "long/longue", book: 5, unit: 6 },
    { de: "warm, heiss", fr: "chaud/chaude", book: 5, unit: 6 },
    { de: "kalt", fr: "froid/froide", book: 5, unit: 6 },
    { de: "Der Mann ist gross.", fr: "Le monsieur est grand.", book: 5, unit: 6 },
    { de: "Die Frau ist gross.", fr: "La dame est grande.", book: 5, unit: 6 },
    { de: "Die Kinder/Knaben sind gross.", fr: "Les enfants/garçons sont grands.", book: 5, unit: 6 },
    { de: "Die Mädchen sind gross.", fr: "Les filles sont grandes.", book: 5, unit: 6 },
    { de: "das Kleidungsstück", fr: "le vêtement", book: 5, unit: 6 },
    { de: "das T-Shirt", fr: "le tee-shirt", book: 5, unit: 6 },
    { de: "der Pullover", fr: "le pull", book: 5, unit: 6 },
    { de: "das Hemd", fr: "la chemise", book: 5, unit: 6 },
    { de: "die Hose", fr: "le pantalon", book: 5, unit: 6 },
    { de: "die Shorts, die kurze Hose", fr: "le short", book: 5, unit: 6 },
    { de: "das Kleid", fr: "la robe", book: 5, unit: 6 },
    { de: "der Rock, der Jupe", fr: "la jupe", book: 5, unit: 6 },
    { de: "die Socke", fr: "la chaussette", book: 5, unit: 6 },
    { de: "der (Halb-)Schuh", fr: "la chaussure", book: 5, unit: 6 },
    { de: "die Jacke", fr: "la veste", book: 5, unit: 6 },
    { de: "der Hut", fr: "le chapeau", book: 5, unit: 6 },
    { de: "die (Schirm-)Mütze", fr: "la casquette", book: 5, unit: 6 },
    { de: "der Mantel", fr: "le manteau", book: 5, unit: 6 },
    { de: "die Uhr", fr: "la montre", book: 5, unit: 6 },
    { de: "die Krawatte", fr: "la cravate", book: 5, unit: 6 },
    { de: "Meine Figur trägt eine rote Hose.", fr: "Mon personnage porte un pantalon rouge.", book: 5, unit: 6 },
    { de: "Wer ist das?", fr: "C'est qui?", book: 5, unit: 6 },
    { de: "Was trägt dein Bauwerk?", fr: "Que porte ton monument?", book: 5, unit: 6 },

    // === DIS DONC! 6 (Оранжевая тема) ===
    // Unit 1
    { de: "der Ritter", fr: "le chevalier", book: 6, unit: 1 },
    { de: "zuverlässig", fr: "fiable", book: 6, unit: 1 },
    // Unit 2
    { de: "die Hexe", fr: "la sorcière", book: 6, unit: 2 },
    { de: "eifersüchtig", fr: "jaloux", book: 6, unit: 2 },
    // Unit 3
    { de: "der Vampir", fr: "le vampire", book: 6, unit: 3 },
    { de: "unsterblich", fr: "immortel", book: 6, unit: 3 },
    // Unit 4
    { de: "das Abenteuer", fr: "l'aventure", book: 6, unit: 4 },
    { de: "die Reise", fr: "le voyage", book: 6, unit: 4 },
    // Unit 5
    { de: "der Berg", fr: "la montagne", book: 6, unit: 5 },
    { de: "der See", fr: "le lac", book: 6, unit: 5 },
    // Unit 6
    { de: "die Zukunft", fr: "l'avenir", book: 6, unit: 6 },
    { de: "der Traum", fr: "le rêve", book: 6, unit: 6 }
];
