const questions = [
    // === DIS DONC! 5 (Зелёная тема) ===
    // Unit 1
    { de: "das Buch", fr: "le livre", book: 5, unit: 1 },
    { de: "das Lineal", fr: "la règle", book: 5, unit: 1 },
    { de: "der Ordner", fr: "le classeur", book: 5, unit: 1 },
    { de: "das Heft", fr: "le cahier", book: 5, unit: 1 },
    { de: "der Bleistift", fr: "le crayon", book: 5, unit: 1 },
    { de: "der Kugelschreiber", fr: "le stylo", book: 5, unit: 1 },
    { de: "der Gummi", fr: "la gomme", book: 5, unit: 1 },
    { de: "die Wandtafel", fr: "le tableau noir", book: 5, unit: 1 },
    { de: "das Etui", fr: "la trousse", book: 5, unit: 1 },
    { de: "der Tisch", fr: "la table", book: 5, unit: 1 },
    { de: "der Stuhl", fr: "la chaise", book: 5, unit: 1 },
    { de: "das Schulfach", fr: "la matière scolaire", book: 5, unit: 1 },
    { de: "Deutsch", fr: "l'allemand", book: 5, unit: 1 },
    { de: "Französisch", fr: "le français", book: 5, unit: 1 },
    { de: "Englisch", fr: "l'anglais", book: 5, unit: 1 },
    { de: "Mathematik", fr: "les mathématiques", book: 5, unit: 1 },
    { de: "die Wochentage", fr: "les jours de la semaine", book: 5, unit: 1 },
    { de: "Montag", fr: "lundi", book: 5, unit: 1 },
    { de: "Dienstag", fr: "mardi", book: 5, unit: 1 },
    { de: "Mittwoch", fr: "mercredi", book: 5, unit: 1 },
    { de: "Donnerstag", fr: "jeudi", book: 5, unit: 1 },
    { de: "Freitag", fr: "vendredi", book: 5, unit: 1 },
    { de: "Samstag", fr: "samedi", book: 5, unit: 1 },
    { de: "Sonntag", fr: "dimanche", book: 5, unit: 1 },
    { de: "eine Schule", fr: "une école", book: 5, unit: 1 },
    { de: "rechnen", fr: "calculer", book: 5, unit: 1 },
    { de: "zeichnen", fr: "dessiner", book: 5, unit: 1 },
    { de: "singen", fr: "chanter", book: 5, unit: 1 },
    { de: "experimentieren", fr: "expérimenter", book: 5, unit: 1 },
    { de: "Französisch sprechen", fr: "parler français", book: 5, unit: 1 },
    
    // Unit 2
    { de: "die Familie", fr: "la famille", book: 5, unit: 2 },
    { de: "ein Kind", fr: "un/une enfant", book: 5, unit: 2 },
    { de: "die Mutter", fr: "la mère, la maman", book: 5, unit: 2 },
    { de: "der Vater", fr: "le père, le papa", book: 5, unit: 2 },
    { de: "die Eltern", fr: "les parents", book: 5, unit: 2 },
    { de: "die Schwester", fr: "la sœur", book: 5, unit: 2 },
    { de: "der Bruder", fr: "le frère", book: 5, unit: 2 },
    { de: "die Grossmutter", fr: "la grand-mère", book: 5, unit: 2 },
    { de: "der Grossvater", fr: "le grand-père", book: 5, unit: 2 },
    { de: "die Grosseltern", fr: "les grands-parents", book: 5, unit: 2 },
    { de: "die Tante", fr: "la tante", book: 5, unit: 2 },
    { de: "ein Onkel", fr: "un oncle", book: 5, unit: 2 },
    { de: "die Cousine", fr: "la cousine", book: 5, unit: 2 },
    { de: "der Cousin", fr: "le cousin", book: 5, unit: 2 },
    { de: "das Baby, das Kleinkind", fr: "le bébé", book: 5, unit: 2 },
    { de: "die Tochter, das Mädchen", fr: "la fille", book: 5, unit: 2 },
    { de: "der Sohn", fr: "le fils", book: 5, unit: 2 },
    { de: "hier ist, da ist", fr: "voici, voilà", book: 5, unit: 2 },
    { de: "er ist, sie ist", fr: "il est, elle est", book: 5, unit: 2 },
    { de: "Lionel ist der Bruder von Nathalie.", fr: "Lionel est le frère de Nathalie.", book: 5, unit: 2 },
    { de: "sie sind", fr: "ils sont, elles sont", book: 5, unit: 2 },
    { de: "das ist", fr: "c'est", book: 5, unit: 2 },
    { de: "Das ist meine Familie.", fr: "C'est ma famille.", book: 5, unit: 2 },
    { de: "das sind", fr: "ce sont", book: 5, unit: 2 },
    { de: "Das sind meine Grosseltern.", fr: "Ce sont mes grands-parents.", book: 5, unit: 2 },
    { de: "wer?", fr: "qui?", book: 5, unit: 2 },
    { de: "er heisst, sie heisst", fr: "il s'appelle, elle s'appelle", book: 5, unit: 2 },
    { de: "sie heissen", fr: "ils s'appellent, elles s'appellent", book: 5, unit: 2 },
    { de: "der Steckbrief", fr: "la fiche personnelle", book: 5, unit: 2 },
    { de: "der Name", fr: "le nom", book: 5, unit: 2 },
    { de: "der Vorname", fr: "le prénom", book: 5, unit: 2 },
    { de: "die Sprache", fr: "la langue", book: 5, unit: 2 },
    { de: "Ich spreche Deutsch, Französisch und Englisch.", fr: "Je parle allemand, français et anglais.", book: 5, unit: 2 },

    // Unit 3
    { de: "die Freizeitbeschäftigung", fr: "le loisir", book: 5, unit: 3 },
    { de: "ein Computer", fr: "un ordinateur", book: 5, unit: 3 },
    { de: "der Fernseher", fr: "la télé", book: 5, unit: 3 },
    { de: "die Spielkonsole", fr: "la console", book: 5, unit: 3 },
    { de: "lesen", fr: "lire", book: 5, unit: 3 },
    { de: "Fussball (Spiel), Fussball spielen", fr: "le foot, faire du foot", book: 5, unit: 3 },
    { de: "das Velo, das Fahrrad", fr: "le vélo", book: 5, unit: 3 },
    { de: "der Ski", fr: "le ski", book: 5, unit: 3 },
    { de: "das Unihockey, Unihockey spielen", fr: "l'unihockey (m), faire de l'unihockey", book: 5, unit: 3 },
    { de: "tanzen", fr: "danser", book: 5, unit: 3 },
    { de: "schwimmen", fr: "nager", book: 5, unit: 3 },
    { de: "die Gitarre, Gitarre spielen", fr: "la guitare, jouer de la guitare", book: 5, unit: 3 },
    { de: "die Flöte", fr: "la flûte", book: 5, unit: 3 },
    { de: "das Klavier, Klavier spielen", fr: "le piano, jouer du piano", book: 5, unit: 3 },
    { de: "draussen spielen", fr: "jouer dehors", book: 5, unit: 3 },
    { de: "ein Tier, die Tiere", fr: "un animal, les animaux (m pl)", book: 5, unit: 3 },
    { de: "das Basteln", fr: "le bricolage", book: 5, unit: 3 },
    { de: "Musik hören", fr: "écouter de la musique", book: 5, unit: 3 },
    { de: "kochen", fr: "faire la cuisine", book: 5, unit: 3 },
    { de: "shoppen", fr: "faire du shopping", book: 5, unit: 3 },
    { de: "Freunde/Freundinnen treffen", fr: "rencontrer des amis/amies", book: 5, unit: 3 },
    { de: "lieben, ich liebe", fr: "aimer, j'aime", book: 5, unit: 3 },
    { de: "sehr gerne haben, ich habe sehr gerne", fr: "adorer, j'adore", book: 5, unit: 3 },
    { de: "meine Leidenschaft ist ...", fr: "ma passion, c'est...", book: 5, unit: 3 },
    { de: "mein Hobby ist ...", fr: "mon hobby, c'est...", book: 5, unit: 3 },
    { de: "ich bin Fan von ...", fr: "je suis fan de...", book: 5, unit: 3 },
    { de: "die Zahl", fr: "le nombre", book: 5, unit: 3 },
    { de: "ein Schüler, eine Schülerin", fr: "un/une élève", book: 5, unit: 3 },
    { de: "der Knabe", fr: "le garçon", book: 5, unit: 3 },
    { de: "das Mädchen, die Tochter", fr: "la fille", book: 5, unit: 3 },

    // Unit 4
    { de: "eine Zutat", fr: "un ingrédient", book: 5, unit: 4 },
    { de: "eine Ananas", fr: "un ananas", book: 5, unit: 4 },
    { de: "die grüne/blaue Traube", fr: "le raisin vert/bleu", book: 5, unit: 4 },
    { de: "die Erdbeere", fr: "la fraise", book: 5, unit: 4 },
    { de: "der weisse Champignon", fr: "le champignon blanc", book: 5, unit: 4 },
    { de: "die Gurkenscheibe", fr: "la rondelle de concombre", book: 5, unit: 4 },
    { de: "die Karotte", fr: "la carotte", book: 5, unit: 4 },
    { de: "die Birne", fr: "la poire", book: 5, unit: 4 },
    { de: "das Ananasblatt", fr: "la feuille d'ananas", book: 5, unit: 4 },
    { de: "die (Kirsch-)Tomate", fr: "la tomate (cerise)", book: 5, unit: 4 },
    { de: "ein wenig Petersilie", fr: "un peu de persil", book: 5, unit: 4 },
    { de: "das Gesicht", fr: "le visage", book: 5, unit: 4 },
    { de: "ein Ohr", fr: "une oreille", book: 5, unit: 4 },
    { de: "die Augen, ein Auge", fr: "les yeux (m pl), un œil", book: 5, unit: 4 },
    { de: "die Haare", fr: "les cheveux (m pl)", book: 5, unit: 4 },
    { de: "der Kopf", fr: "la tête", book: 5, unit: 4 },
    { de: "die Nase", fr: "le nez", book: 5, unit: 4 },
    { de: "der Mund", fr: "la bouche", book: 5, unit: 4 },
    { de: "die Zitronenscheibe", fr: "la rondelle de citron", book: 5, unit: 4 },
    { de: "Für die Nase nehme ich eine Karotte.", fr: "Pour le nez, je prends une carotte.", book: 5, unit: 4 },
    { de: "Was ist das?", fr: "C'est quoi?", book: 5, unit: 4 },
    { de: "die Banane", fr: "la banane", book: 5, unit: 4 },
    { de: "die Nudeln", fr: "les nouilles (f pl)", book: 5, unit: 4 },
    { de: "Spiesse eine Traube auf.", fr: "Pique un raisin.", book: 5, unit: 4 },
    { de: "Befestige die Traube an der Birne.", fr: "Fixe le raisin sur la poire.", book: 5, unit: 4 },
    { de: "Schneide (halbiere) die Ananas.", fr: "Coupe l'ananas (en deux).", book: 5, unit: 4 },
    { de: "Stelle/Lege die Erdbeere auf den Teller.", fr: "Pose la fraise sur l'assiette.", book: 5, unit: 4 },
    { de: "Nimm eine Birne für den Körper.", fr: "Prends une poire pour le corps.", book: 5, unit: 4 },
    { de: "Du schneidest. Schneide!", fr: "Tu coupes. Coupe.", book: 5, unit: 4 },
    { de: "Ihr schneidet. Schneidet!", fr: "Vous coupez. Coupez.", book: 5, unit: 4 },
    { de: "ein Alphabet", fr: "un alphabet", book: 5, unit: 4 },
    { de: "die Suppe", fr: "la soupe", book: 5, unit: 4 },
    { de: "der Buchstabe", fr: "la lettre", book: 5, unit: 4 },

    // Unit 5
    { de: "der Wolf", fr: "le loup", book: 5, unit: 5 },
    { de: "der Igel", fr: "le hérisson", book: 5, unit: 5 },
    { de: "das Murmeltier", fr: "la marmotte", book: 5, unit: 5 },
    { de: "eine Biene", fr: "une abeille", book: 5, unit: 5 },
    { de: "ein Wohnort", fr: "une adresse", book: 5, unit: 5 },
    { de: "die Grösse", fr: "la taille", book: 5, unit: 5 },
    { de: "das Gewicht", fr: "le poids", book: 5, unit: 5 },
    { de: "die Nahrung", fr: "la nourriture", book: 5, unit: 5 },
    { de: "hundert", fr: "cent", book: 5, unit: 5 },
    { de: "tausend", fr: "mille", book: 5, unit: 5 },
    { de: "die Katze", fr: "le chat", book: 5, unit: 5 },
    { de: "das Pferd", fr: "le cheval", book: 5, unit: 5 },
    { de: "das Schwein", fr: "le cochon", book: 5, unit: 5 },
    { de: "eine Schnecke", fr: "un escargot", book: 5, unit: 5 },
    { de: "das Kaninchen", fr: "le lapin", book: 5, unit: 5 },
    { de: "der Papagei", fr: "le perroquet", book: 5, unit: 5 },
    { de: "der Fisch", fr: "le poisson", book: 5, unit: 5 },
    { de: "die Kuh", fr: "la vache", book: 5, unit: 5 },
    { de: "die Farbe", fr: "la couleur", book: 5, unit: 5 },
    { de: "weiss", fr: "blanc/blanche", book: 5, unit: 5 },
    { de: "grau", fr: "gris/grise", book: 5, unit: 5 },
    { de: "schwarz", fr: "noir/noire", book: 5, unit: 5 },
    { de: "braun", fr: "brun/brune, marron", book: 5, unit: 5 },
    { de: "blau", fr: "bleu/bleue", book: 5, unit: 5 },
    { de: "grün", fr: "vert/verte", book: 5, unit: 5 },
    { de: "rot", fr: "rouge", book: 5, unit: 5 },
    { de: "gelb", fr: "jaune", book: 5, unit: 5 },
    { de: "rosa", fr: "rose", book: 5, unit: 5 },
    { de: "violett", fr: "violet/violette", book: 5, unit: 5 },
    { de: "orange", fr: "orange", book: 5, unit: 5 },
    { de: "Er/Sie lebt in den Bergen Europas.", fr: "Il/Elle vit dans les montagnes en Europe.", book: 5, unit: 5 },
    { de: "Er/Sie frisst (isst) Früchte.", fr: "Il/Elle mange des fruits.", book: 5, unit: 5 },
    { de: "Er/Sie misst 45 bis 60 Zentimeter.", fr: "Il/Elle mesure de 45 à 60 centimètres.", book: 5, unit: 5 },
    { de: "Er/Sie wiegt zwischen 5 und 10 Kilogramm.", fr: "Il/Elle pèse entre 5 et 10 kilos.", book: 5, unit: 5 },
    { de: "Er/Sie hat einen Schnabel.", fr: "Il/Elle a un bec.", book: 5, unit: 5 },
    { de: "Er/Sie ist grau und braun.", fr: "Il/Elle est gris/e et brun/e.", book: 5, unit: 5 },
    { de: "Welche Farbe hat das Schwein?", fr: "De quelle couleur est le cochon?", book: 5, unit: 5 },
    
    // Unit 6
    { de: "die Stadt", fr: "la ville", book: 5, unit: 6 },
    { de: "das Land", fr: "le pays", book: 5, unit: 6 },
    { de: "das Bauwerk", fr: "le monument", book: 5, unit: 6 },
    { de: "der Turm", fr: "la tour", book: 5, unit: 6 },
    { de: "gross", fr: "grand/grande", book: 5, unit: 6 },
    { de: "klein", fr: "petit/petite", book: 5, unit: 6 },
    { de: "rund", fr: "rond/ronde", book: 5, unit: 6 },
    { de: "rechteckig", fr: "rectangulaire", book: 5, unit: 6 },
    { de: "kurz", fr: "court/courte", book: 5, unit: 6 },
    { de: "lang", fr: "long/longue", book: 5, unit: 6 },
    { de: "warm, heiss", fr: "chaud/chaude", book: 5, unit: 6 },
    { de: "kalt", fr: "froid/froide", book: 5, unit: 6 },
    { de: "Der Mann ist gross.", fr: "Le monsieur est grand.", book: 5, unit: 6 },
    { de: "Die Frau ist gross.", fr: "La dame est grande.", book: 5, unit: 6 },
    { de: "Die Kinder/Knaben sind gross.", fr: "Les enfants/garçons sont grands.", book: 5, unit: 6 },
    { de: "Die Mädchen sind gross.", fr: "Les filles sont grandes.", book: 5, unit: 6 },
    { de: "das Kleidungsstück", fr: "le vêtement", book: 5, unit: 6 },
    { de: "das T-Shirt", fr: "le tee-shirt", book: 5, unit: 6 },
    { de: "der Pullover", fr: "le pull", book: 5, unit: 6 },
    { de: "das Hemd", fr: "la chemise", book: 5, unit: 6 },
    { de: "die Hose", fr: "le pantalon", book: 5, unit: 6 },
    { de: "die Shorts, die kurze Hose", fr: "le short", book: 5, unit: 6 },
    { de: "das Kleid", fr: "la robe", book: 5, unit: 6 },
    { de: "der Rock, der Jupe", fr: "la jupe", book: 5, unit: 6 },
    { de: "die Socke", fr: "la chaussette", book: 5, unit: 6 },
    { de: "der (Halb-)Schuh", fr: "la chaussure", book: 5, unit: 6 },
    { de: "die Jacke", fr: "la veste", book: 5, unit: 6 },
    { de: "der Hut", fr: "le chapeau", book: 5, unit: 6 },
    { de: "die (Schirm-)Mütze", fr: "la casquette", book: 5, unit: 6 },
    { de: "der Mantel", fr: "le manteau", book: 5, unit: 6 },
    { de: "die Uhr", fr: "la montre", book: 5, unit: 6 },
    { de: "die Krawatte", fr: "la cravate", book: 5, unit: 6 },
    { de: "Meine Figur trägt eine rote Hose.", fr: "Mon personnage porte un pantalon rouge.", book: 5, unit: 6 },
    { de: "Wer ist das?", fr: "C'est qui?", book: 5, unit: 6 },
    { de: "Was trägt dein Bauwerk?", fr: "Que porte ton monument?", book: 5, unit: 6 },

   const questions = [
    // === DIS DONC! 6 (Оранжевая тема) ===
    // Unit 1
    { de: "die Hausaufgaben machen", fr: "faire les devoirs (m pl)", book: 6, unit: 1 },
    { de: "zu Hause", fr: "à la maison", book: 6, unit: 1 },
    { de: "in der Schule", fr: "à l'école", book: 6, unit: 1 },
    { de: "auf einer Insel", fr: "sur une île", book: 6, unit: 1 },
    { de: "in der Metro, in der U-Bahn", fr: "dans le métro", book: 6, unit: 1 },
    { de: "draußen", fr: "dehors", book: 6, unit: 1 },
    { de: "im Wasser", fr: "dans l'eau", book: 6, unit: 1 },
    { de: "auf dem Tabletcomputer", fr: "sur la tablette (numérique)", book: 6, unit: 1 },
    { de: "Wie?", fr: "Comment?", book: 6, unit: 1 },
    { de: "Wo?", fr: "Où?", book: 6, unit: 1 },
    { de: "Wann?", fr: "Quand?", book: 6, unit: 1 },
    { de: "Was?", fr: "Quoi?", book: 6, unit: 1 },
    { de: "Was machst du?", fr: "Qu'est-ce que tu fais?", book: 6, unit: 1 },
    { de: "Wer?", fr: "Qui?", book: 6, unit: 1 },
    { de: "auf", fr: "sur", book: 6, unit: 1 },
    { de: "unter", fr: "sous", book: 6, unit: 1 },
    { de: "in", fr: "dans", book: 6, unit: 1 },
    { de: "in der Mitte von", fr: "au milieu de", book: 6, unit: 1 },
    { de: "in, bei, zu, an", fr: "à", book: 6, unit: 1 },
    { de: "vor", fr: "devant", book: 6, unit: 1 },
    { de: "hinter", fr: "derrière", book: 6, unit: 1 },
    { de: "zwischen ... und", fr: "entre ... et", book: 6, unit: 1 },
    { de: "schlafen", fr: "dormir", book: 6, unit: 1 },
    { de: "lesen", fr: "lire", book: 6, unit: 1 },
    { de: "am Meer", fr: "à la mer", book: 6, unit: 1 },
    { de: "unter einem Baum", fr: "sous un arbre", book: 6, unit: 1 },
    { de: "mit meinem Freund/meiner Freundin", fr: "avec mon ami/amie", book: 6, unit: 1 },
    { de: "alleine", fr: "seul/seule", book: 6, unit: 1 },
    { de: "der Morgen, am Morgen", fr: "le matin", book: 6, unit: 1 },
    { de: "am Mittag", fr: "à midi", book: 6, unit: 1 },
    { de: "der Nachmittag, am Nachmittag", fr: "l'après-midi (m/f)", book: 6, unit: 1 },
    { de: "der Abend, am Abend", fr: "le soir", book: 6, unit: 1 },
    { de: "die Nacht, in der Nacht", fr: "la nuit", book: 6, unit: 1 },
    { de: "das Wochenende, am Wochenende", fr: "le week-end", book: 6, unit: 1 },
    { de: "die Welt", fr: "le monde", book: 6, unit: 1 },
    { de: "überall", fr: "partout", book: 6, unit: 1 },
    { de: "der Ritter", fr: "le chevalier", book: 6, unit: 1 },
    { de: "zuverlässig", fr: "fiable", book: 6, unit: 1 },

    // Unit 2
    { de: "das Haus", fr: "la maison", book: 6, unit: 2 },
    { de: "eine Wohnung", fr: "un appartement", book: 6, unit: 2 },
    { de: "die Küche", fr: "la cuisine", book: 6, unit: 2 },
    { de: "das Wohnzimmer", fr: "le salon", book: 6, unit: 2 },
    { de: "das Zimmer, das Schlafzimmer", fr: "la chambre", book: 6, unit: 2 },
    { de: "die Toilette, das WC", fr: "les toilettes (f pl), le WC", book: 6, unit: 2 },
    { de: "das Badezimmer", fr: "la salle de bains", book: 6, unit: 2 },
    { de: "ein Stockwerk", fr: "un étage", book: 6, unit: 2 },
    { de: "das Erdgeschoss", fr: "le rez-de-chaussée", book: 6, unit: 2 },
    { de: "das Untergeschoss", fr: "le sous-sol", book: 6, unit: 2 },
    { de: "Ich wohne im ersten Stock.", fr: "J'habite au premier étage.", book: 6, unit: 2 },
    { de: "Du wohnst im zweiten Stock.", fr: "Tu habites au deuxième étage.", book: 6, unit: 2 },
    { de: "Er wohnt im dritten Stock.", fr: "Il habite au troisième étage.", book: 6, unit: 2 },
    { de: "arbeiten", fr: "travailler", book: 6, unit: 2 },
    { de: "Ich arbeite in der Apotheke.", fr: "Je travaille à la pharmacie.", book: 6, unit: 2 },
    { de: "auf", fr: "sur", book: 6, unit: 2 },
    { de: "unter", fr: "sous", book: 6, unit: 2 },
    { de: "in", fr: "dans", book: 6, unit: 2 },
    { de: "in der Mitte von", fr: "au milieu de", book: 6, unit: 2 },
    { de: "in, an, zu, bei", fr: "à", book: 6, unit: 2 },
    { de: "vor", fr: "devant", book: 6, unit: 2 },
    { de: "hinter", fr: "derrière", book: 6, unit: 2 },
    { de: "zwischen ... und", fr: "entre ... et", book: 6, unit: 2 },
    { de: "oben", fr: "en haut", book: 6, unit: 2 },
    { de: "unten", fr: "en bas", book: 6, unit: 2 },
    { de: "die Türe", fr: "la porte", book: 6, unit: 2 },
    { de: "das Fenster", fr: "la fenêtre", book: 6, unit: 2 },
    { de: "das Bett", fr: "le lit", book: 6, unit: 2 },
    { de: "der Tisch", fr: "la table", book: 6, unit: 2 },
    { de: "der Stuhl", fr: "la chaise", book: 6, unit: 2 },
    { de: "ein Gestell", fr: "une étagère", book: 6, unit: 2 },
    { de: "ein Schrank", fr: "une armoire", book: 6, unit: 2 },
    { de: "der Sessel", fr: "le fauteuil", book: 6, unit: 2 },
    { de: "der Teppich", fr: "le tapis", book: 6, unit: 2 },
    { de: "die Kommode", fr: "la commode", book: 6, unit: 2 },
    { de: "die Pflanze", fr: "la plante", book: 6, unit: 2 },
    { de: "ein Poster", fr: "une affiche", book: 6, unit: 2 },
    { de: "links von der Lampe", fr: "à gauche de la lampe", book: 6, unit: 2 },
    { de: "links vom Klavier", fr: "à gauche du piano", book: 6, unit: 2 },
    { de: "rechts vom Gestell", fr: "à droite de l'étagère", book: 6, unit: 2 },
    { de: "die Hexe", fr: "la sorcière", book: 6, unit: 2 },
    { de: "eifersüchtig", fr: "jaloux", book: 6, unit: 2 },

    // Unit 3
    { de: "auf die Waage steigen", fr: "monter sur la balance", book: 6, unit: 3 },
    { de: "denken", fr: "penser", book: 6, unit: 3 },
    { de: "trinken", fr: "boire", book: 6, unit: 3 },
    { de: "essen", fr: "manger", book: 6, unit: 3 },
    { de: "(hin-)legen, setzen, stellen", fr: "mettre", book: 6, unit: 3 },
    { de: "schauen", fr: "regarder", book: 6, unit: 3 },
    { de: "das Jogging, das Laufen", fr: "la course à pied", book: 6, unit: 3 },
    { de: "joggen, laufen", fr: "faire de la course à pied/faire du jogging", book: 6, unit: 3 },
    { de: "bleiben", fr: "rester", book: 6, unit: 3 },
    { de: "das Fitness/die Sporthalle", fr: "le gymnase/la salle de gymnastique", book: 6, unit: 3 },
    { de: "finden", fr: "trouver", book: 6, unit: 3 },
    { de: "zu schwierig", fr: "trop difficile", book: 6, unit: 3 },
    { de: "gehen", fr: "aller", book: 6, unit: 3 },
    { de: "rennen", fr: "courir", book: 6, unit: 3 },
    { de: "die Biskuitschachtel/-dose", fr: "la boîte à biscuits", book: 6, unit: 3 },
    { de: "leicht", fr: "léger/légère", book: 6, unit: 3 },
    { de: "vergessen", fr: "oublier", book: 6, unit: 3 },
    { de: "wie", fr: "comme", book: 6, unit: 3 },
    { de: "feiern", fr: "faire la fête", book: 6, unit: 3 },
    { de: "sein", fr: "être", book: 6, unit: 3 },
    { de: "haben", fr: "avoir", book: 6, unit: 3 },
    { de: "der Hunger", fr: "la faim", book: 6, unit: 3 },
    { de: "Ich habe Hunger.", fr: "J'ai faim.", book: 6, unit: 3 },
    { de: "neu", fr: "nouveau/nouvelle", book: 6, unit: 3 },
    { de: "rechte(-r, -s)", fr: "droit/droite", book: 6, unit: 3 },
    { de: "linke(-r, -s)", fr: "gauche/gauche", book: 6, unit: 3 },
    { de: "der Fuss", fr: "le pied", book: 6, unit: 3 },
    { de: "mit dem linken Fuss stampfen", fr: "taper du pied gauche", book: 6, unit: 3 },
    { de: "der Finger", fr: "le doigt", book: 6, unit: 3 },
    { de: "mit den Fingern schnippen", fr: "claquer des doigts", book: 6, unit: 3 },
    { de: "die Hand", fr: "la main", book: 6, unit: 3 },
    { de: "in die Hände klatschen", fr: "frapper dans les mains", book: 6, unit: 3 },
    { de: "die Brust", fr: "la poitrine", book: 6, unit: 3 },
    { de: "mit der rechten Hand auf die Brust schlagen", fr: "taper avec la main droite sur la poitrine", book: 6, unit: 3 },
    { de: "der Oberschenkel", fr: "la cuisse", book: 6, unit: 3 },
    { de: "mit der linken Hand auf den linken Oberschenkel schlagen", fr: "frapper la main gauche sur la cuisse gauche", book: 6, unit: 3 },
    { de: "die Wange", fr: "la joue", book: 6, unit: 3 },
    { de: "auf die Wangen schlagen", fr: "frapper sur les joues", book: 6, unit: 3 },
    { de: "der Vampir", fr: "le vampire", book: 6, unit: 3 },
    { de: "unsterblich", fr: "immortel", book: 6, unit: 3 },

    // Unit 4
    { de: "das typische Gericht", fr: "le plat typique", book: 6, unit: 4 },
    { de: "die Milch", fr: "le lait", book: 6, unit: 4 },
    { de: "der Zug", fr: "le train", book: 6, unit: 4 },
    { de: "das Auto", fr: "la voiture", book: 6, unit: 4 },
    { de: "der Strand", fr: "la plage", book: 6, unit: 4 },
    { de: "eine Vorspeise", fr: "une entrée", book: 6, unit: 4 },
    { de: "der grüne Salat", fr: "la salade verte", book: 6, unit: 4 },
    { de: "die Gemüsesuppe", fr: "la soupe aux légumes", book: 6, unit: 4 },
    { de: "der Teigboden mit Belag (salzig oder süss)", fr: "la tarte", book: 6, unit: 4 },
    { de: "der Rohschinken", fr: "le jambon cru", book: 6, unit: 4 },
    { de: "der Hauptgang / die Hauptgänge", fr: "le plat principal/les plats principaux", book: 6, unit: 4 },
    { de: "der Reis", fr: "le riz", book: 6, unit: 4 },
    { de: "die Nudeln", fr: "les nouilles (f pl)", book: 6, unit: 4 },
    { de: "die Pommes frites", fr: "les frites (f pl)", book: 6, unit: 4 },
    { de: "der Kartoffelstock", fr: "la purée de pommes de terre", book: 6, unit: 4 },
    { de: "ein Schnitzel", fr: "une escalope", book: 6, unit: 4 },
    { de: "das Hacksteak", fr: "le steak haché", book: 6, unit: 4 },
    { de: "das Dessert", fr: "le dessert", book: 6, unit: 4 },
    { de: "der Pfannkuchen, die Crêpe", fr: "la crêpe", book: 6, unit: 4 },
    { de: "der Schokoladenkuchen", fr: "le gâteau au chocolat", book: 6, unit: 4 },
    { de: "das Eis", fr: "la glace", book: 6, unit: 4 },
    { de: "das Getränk", fr: "la boisson", book: 6, unit: 4 },
    { de: "ein Mineralwasser", fr: "une eau minérale", book: 6, unit: 4 },
    { de: "der Kaffee", fr: "le café", book: 6, unit: 4 },
    { de: "der Eistee", fr: "le thé froid", book: 6, unit: 4 },
    { de: "Haben Sie einen Tisch für zwei Personen?", fr: "Vous avez une table pour deux personnes?", book: 6, unit: 4 },
    { de: "Hier ist die Speisekarte.", fr: "Voici le menu.", book: 6, unit: 4 },
    { de: "Als Vorspeise haben wir ...", fr: "Comme entrée, nous avons...", book: 6, unit: 4 },
    { de: "Als Hauptgang haben wir ...", fr: "Comme plat principal, nous avons...", book: 6, unit: 4 },
    { de: "Als Dessert haben wir ...", fr: "Comme dessert, nous avons...", book: 6, unit: 4 },
    { de: "bestellen", fr: "commander", book: 6, unit: 4 },
    { de: "Was nehmen Sie?", fr: "Qu'est-ce que vous prenez?", book: 6, unit: 4 },
    { de: "ich nehme", fr: "je prends", book: 6, unit: 4 },
    { de: "für mich", fr: "pour moi", book: 6, unit: 4 },
    { de: "bitte", fr: "s'il te plaît/s'il vous plaît", book: 6, unit: 4 },
    { de: "Ein/Eine ..., was ist das?", fr: "Un/Une..., qu'est-ce que c'est?", book: 6, unit: 4 },
    { de: "Ich empfehle den Tagesteller.", fr: "Je recommande le plat du jour.", book: 6, unit: 4 },
    { de: "Es war lecker.", fr: "C'était délicieux!", book: 6, unit: 4 },
    { de: "eine Rechnung", fr: "une addition", book: 6, unit: 4 },

    // Unit 5
    { de: "der Wolf", fr: "le loup", book: 6, unit: 5 },
    { de: "der Igel", fr: "le hérisson", book: 6, unit: 5 },
    { de: "das Murmeltier", fr: "la marmotte", book: 6, unit: 5 },
    { de: "eine Biene", fr: "une abeille", book: 6, unit: 5 },
    { de: "ein Wohnort", fr: "une adresse", book: 6, unit: 5 },
    { de: "die Grösse", fr: "la taille", book: 6, unit: 5 },
    { de: "das Gewicht", fr: "le poids", book: 6, unit: 5 },
    { de: "die Nahrung", fr: "la nourriture", book: 6, unit: 5 },
    { de: "hundert", fr: "cent", book: 6, unit: 5 },
    { de: "tausend", fr: "mille", book: 6, unit: 5 },
    { de: "die Katze", fr: "le chat", book: 6, unit: 5 },
    { de: "das Pferd", fr: "le cheval", book: 6, unit: 5 },
    { de: "das Schwein", fr: "le cochon", book: 6, unit: 5 },
    { de: "eine Schnecke", fr: "un escargot", book: 6, unit: 5 },
    { de: "das Kaninchen", fr: "le lapin", book: 6, unit: 5 },
    { de: "der Papagei", fr: "le perroquet", book: 6, unit: 5 },
    { de: "der Fisch", fr: "le poisson", book: 6, unit: 5 },
    { de: "die Kuh", fr: "la vache", book: 6, unit: 5 },
    { de: "die Farbe", fr: "la couleur", book: 6, unit: 5 },
    { de: "weiss", fr: "blanc/blanche", book: 6, unit: 5 },
    { de: "grau", fr: "gris/grise", book: 6, unit: 5 },
    { de: "schwarz", fr: "noir/noire", book: 6, unit: 5 },
    { de: "braun", fr: "brun/brune, marron", book: 6, unit: 5 },
    { de: "blau", fr: "bleu/bleue", book: 6, unit: 5 },
    { de: "grün", fr: "vert/verte", book: 6, unit: 5 },
    { de: "rot", fr: "rouge", book: 6, unit: 5 },
    { de: "gelb", fr: "jaune", book: 6, unit: 5 },
    { de: "rosa", fr: "rose", book: 6, unit: 5 },
    { de: "violett", fr: "violet/violette", book: 6, unit: 5 },
    { de: "orange", fr: "orange", book: 6, unit: 5 },
    { de: "Er/Sie lebt in den Bergen Europas.", fr: "Il/Elle vit dans les montagnes en Europe.", book: 6, unit: 5 },
    { de: "Er/Sie frisst (isst) Früchte.", fr: "Il/Elle mange des fruits.", book: 6, unit: 5 },
    { de: "Er/Sie misst 45 bis 60 Zentimeter.", fr: "Il/Elle mesure de 45 à 60 centimètres.", book: 6, unit: 5 },
    { de: "Er/Sie wiegt zwischen 5 und 10 Kilogramm.", fr: "Il/Elle pèse entre 5 et 10 kilos.", book: 6, unit: 5 },
    { de: "Er/Sie hat einen Schnabel.", fr: "Il/Elle a un bec.", book: 6, unit: 5 },
    { de: "Er/Sie ist grau und braun.", fr: "Il/Elle est gris/e et brun/e.", book: 6, unit: 5 },
    { de: "Welche Farbe hat das Schwein?", fr: "De quelle couleur est le cochon?", book: 6, unit: 5 },

    // Unit 6
    { de: "das Kino", fr: "le cinéma", book: 6, unit: 6 },
    { de: "Ich bin ein Kinostar.", fr: "Je suis une star de cinéma.", book: 6, unit: 6 },
    { de: "eine Spinne", fr: "une araignée", book: 6, unit: 6 },
    { de: "Er kann riesige Sprünge machen.", fr: "Il peut faire des sauts énormes.", book: 6, unit: 6 },
    { de: "ein Feind", fr: "un ennemi", book: 6, unit: 6 },
    { de: "flink", fr: "agile/agile", book: 6, unit: 6 },
    { de: "zuverlässig", fr: "fiable/fiable", book: 6, unit: 6 },
    { de: "der Ritter", fr: "le chevalier", book: 6, unit: 6 },
    { de: "mutig", fr: "courageux/courageuse", book: 6, unit: 6 },
    { de: "der Mut", fr: "le courage", book: 6, unit: 6 },
    { de: "ehrlich", fr: "honnête/honnête", book: 6, unit: 6 },
    { de: "Er will seinem Volk helfen.", fr: "Il veut aider son peuple.", book: 6, unit: 6 },
    { de: "grausam", fr: "cruel/cruelle", book: 6, unit: 6 },
    { de: "böse", fr: "méchant/méchante", book: 6, unit: 6 },
    { de: "die Hexe", fr: "la sorcière", book: 6, unit: 6 },
    { de: "eifersüchtig", fr: "jaloux/jalouse", book: 6, unit: 6 },
    { de: "Sie kann auf einem Besen fliegen.", fr: "Elle peut voler sur un balai.", book: 6, unit: 6 },
    { de: "der Vampir", fr: "le vampire", book: 6, unit: 6 },
    { de: "unsterblich", fr: "immortel/immortelle", book: 6, unit: 6 },
    { de: "sich verwandeln in", fr: "se transformer en", book: 6, unit: 6 },
    { de: "Naturgewalten manipulieren", fr: "manipuler les forces naturelles (f pl)", book: 6, unit: 6 },
    { de: "schwatzhaft", fr: "bavard/bavarde", book: 6, unit: 6 },
    { de: "ehrgeizig", fr: "ambitieux/ambitieuse", book: 6, unit: 6 },
    { de: "Sie hat ein grosses Herz.", fr: "Elle a un grand cœur.", book: 6, unit: 6 },
    { de: "Sie hilft Probleme zu lösen.", fr: "Elle aide à résoudre des problèmes.", book: 6, unit: 6 },
    { de: "Sie kann Gefühle verstehen.", fr: "Elle peut comprendre les émotions.", book: 6, unit: 6 },
    { de: "der Held/die Heldin", fr: "le héros/l'héroïne (f)", book: 6, unit: 6 },
    { de: "riesig", fr: "géant/géante", book: 6, unit: 6 },
    { de: "schön", fr: "beau/belle", book: 6, unit: 6 },
    { de: "Er hat eine aussergewöhnliche Kraft.", fr: "Il a une force extraordinaire.", book: 6, unit: 6 },
    { de: "gewalttätig", fr: "violent/violente", book: 6, unit: 6 }
];
